# .gitlab-ci.yml

stages:
  - sync

sync:
  stage: sync
  script:
    - git clone https://github.com/abhishekpandaOfficial/Apple_Microservice.git github-repo
    - cd github-repo
    - git config user.email "your-email@example.com"
    - git config user.name "Your Name"
    - git fetch origin
    - git checkout -b $CI_COMMIT_REF_NAME
    - cp -r ../. .
    - git add .
    - git commit -m "Sync changes from GitLab"
    - git push origin $CI_COMMIT_REF_NAME
